### ISSUE TITLE
Curious about your future experiments

### ISSUE THREAD

**Issue by dumblob** [cbeo/weft#1]
Thanks for these experiments! I've again learned something new.

I wonder whether you plan to further experiment with propagation networks?

I can see some shallow resemblance of "pipe" languages but I value the formalism of propagation networks and would like to see more of its edge cases etc.

**Comment by cbeo** [comment]
I'd like to, someday. I had been reading Alexey Andreyevich Radul's 2009 PhD Thesis and "following along" in Common Lisp. If you are currently surfing a wave of curiosity and interest, and want to keep going before you lose it, I suggest that you too dip into his thesis. 

> Propagation` Networks: A Flexible and Expressive Substrate for Computation

Looking over the code in this repo I can see that I didn't even begin fiddling with data provenance and backtracking, the most interesting aspect of the theory IMO.  

Anyway, cool that you got something out of this repo's chronicle of my attentional wanderings.

**Comment by dumblob** [comment]
> > Propagation` Networks: A Flexible and Expressive Substrate for Computation
> 
> Looking over the code in this repo I can see that I didn't even begin fiddling with data provenance and backtracking, the most interesting aspect of the theory IMO.

Ok, I'll take a look.

Feel free to close this issue if you don't plan to get back to this during the upcoming weeks/months :wink:.

**Comment by cbeo** [comment]
I'll leave it open.  That way,  Tin six months or a year or two years from now, when I eventually dig back in, I can reply and maybe we can pick the conversation back up with more to talk about.
